### PR TITLE
Update New_salad.md

### PR DESCRIPTION
**Pull request by YingxiaoYan**
Add lemon in the salad

### CODE REVIEW

**Comment by joh4nd** [comment]
Hi @YingxiaoYan, yum, nice recipy! Are you sure that you do not want to add any other ingredients to the salad?

**Comment by joh4nd** [comment]
Because I am not sure that you saw my comments I will just merge it anyway :)

**Review by amidimohsen — CHANGES_REQUESTED** [review]
Add some wordings in the instruction section.

**Review by joh4nd — APPROVED** [review]

**Review by joh4nd — APPROVED** [review]
I suggested some changes in the next commit.

**Review by joh4nd — APPROVED** [review]

**Pull request merged**
